# Generated by Django 3.2.19 on 2023-07-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='project_name',
        ),
        migrations.AddField(
            model_name='assignment',
            name='project_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
