# Generated by Django 3.2.19 on 2023-07-22 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0004_auto_20230722_0543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='assigned_user_id',
            new_name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='assigned_user_email',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='project_name',
        ),
    ]
