# Generated by Django 3.2.23 on 2023-11-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0005_auto_20230722_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assigned_to',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
